name: Auto build Unicons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Configure auto_build
        run: |
          cd auto_build 
          npm install
          npm install -g fontello-cli

      - name: Obtain all SVG files from Unicons
        run: |
          cd auto_build
          cd scripts
          sh get_line_icons_in_svg.sh
          cd ..
          cd scripts
          sh rename_line_icons.sh
      
      - name: Generate config files for each style
        run: |
          cd auto_build
          npm start

      - name: Generate ttf font and Dart class for UniconsLine
        if: always()
        run: |
          cd auto_build
          cd output
          npx fontello-cli --config unicons_line_config.json --host https://www.fluttericon.com/ install
          npx fontello-cli --config unicons_line_config.json --host https://www.fluttericon.com/ install
          rm .fontello-session

      - name: Generate ttf font and Dart class for UniconsSolid
        if: always()
        run: |
          cd auto_build
          cd output
          npx fontello-cli --config unicons_solid_config.json --host https://www.fluttericon.com/ install
          npx fontello-cli --config unicons_solid_config.json --host https://www.fluttericon.com/ install
          rm .fontello-session

      - name: Generate ttf font and Dart class for UniconsThinline
        if: always()
        run: |
          cd auto_build
          cd output
          npx fontello-cli --config unicons_thinline_config.json --host https://www.fluttericon.com/ install
          npx fontello-cli --config unicons_thinline_config.json --host https://www.fluttericon.com/ install
          rm .fontello-session
