name: Auto build Unicons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Configure auto_build
        run: |
          cd auto_build 
          npm install
          npm install -g fontello-cli

      - name: Obtain all SVG files from Unicons
        run: |
          ls
          cd scripts
          sh get_line_icons_in_svg.sh
          cd ..
          cd scripts
          sh rename_line_icons.sh
          cd ..
      
      - name: Generate config files for each style
        run: |
          npm start

      

